### ISSUE TITLE
Prerequisites for .app passed into packapp.zsh?

### ISSUE THREAD

**Issue by xrd** [smittytone/scripts#2]
I've been reading into your packapp.zsh script. One thing I notice is that this script only uses the "Installer ID" cert, and does not do anything with the (logically "associated") "Application ID" cert. 

If I understand the signing process correctly, you use the "Application ID" script to codesign the application (and the dependent dylibs in frameworks, etc). 

Is this a prerequisite process before calling your script? I assume so, but I am unsure how to verify this.

I've been trying to use a combination of the `codesign` utilities, or the `macdeployqt` script (my app is a QT based application) and the associated flags (`-s` for `codesign` with perhaps `--deep` or ` -codesign` of macdeployqt or `create-dmg --codesign`). But, I'm unsure how to verify things worked correctly so that packapp.zsh succeeds. 

Right now I get an error from packapp.zsh that says:

```
...
myapp.app: rejected
source: unnotarized developer ID
...
```

I assume this means my app is not ready yet for notarization, but the message is a bit cryptic.

Any suggestions? Thank you.

**Comment by smittytone** [comment]
The error is what Apple's notarization server provides. I would first try calling the script with the -v flag and see if that yields any clarity.

I use the script solely for a couple of apps that I build in Xcode: it generates an Installer package from the compiled app and notarizes it. That's why it takes a cert of type 'Developer ID Installer'. The app itself is signed at compile time by Xcode. I don't know the QT process, but it may be there's a disconnect between the cert your build
script is using to sign myapp.app and the cert you're passing to packapp.zsh

**Comment by xrd** [comment]
Thanks, I appreciate your help!
